#!/usr/bin/bash

PS1='\u@\h:\W$(__git_ps1 " (%s)")$ '
export HISTIGNORE="&:[bf]g:exit"
export HISTFILESIZE=50000
export EDITOR=vim
shopt -s histappend

# Environment #############################
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export GOBIN="~/Projects/golang/bin"
export HEROKU_BIN=/usr/local/heroku/bin
export NPM_BIN=/usr/local/share/npm/bin
export POSTGRESAPP=/Applications/Postgres.app/Contents/MacOS/bin
export PATH="~/bin:$POSTGRESAPP:$PATH:$NPM_BIN:$HEROKU_BIN"
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"
export PAGER=less
export LESS="-RSXF --tabs=4"

# Git Settings #############################
export GITHUB="git@github.com"

# Command Aliases ##########################
alias firefox=/Applications/Firefox.app/Contents/MacOS/firefox-bin
alias photoshop="open -a /Applications/Adobe\ Creative\ Suite\ 3/Adobe\ Photoshop\ CS3/Adobe\ Photoshop\ CS3.app/"
alias preview="open -a preview"
alias dotfiles="cd ~/.dotfiles"
alias gr=gitroot
alias g=git
alias gti=git
alias rails-src="cd ~/Projects/rails"
alias tmr="tmux attach-session"

function r()
{
  if [ -e .zeus.sock ] && [ "$1" = "g" ]; then
    zeus $*
  else
    rails $*
  fi
}

# Weirdo Mac Aliases ##########################
alias md5sum=md5

# Include secured settings file
source ~/.dotfiles/secure/env.sh
source ~/.dotfiles/git/git-completion.bash
source ~/.dotfiles/git/git-prompt.sh
source ~/.dotfiles/git/helpers.sh

for i in $(find ~/.dotfiles/bash.d -name "*.sh"); do
  if [ -r $i ]; then
    . $i
  fi
done
unset i

check_ssh_agent

# RVM - Ruby Version Manager
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" && cd .

# End of file stuff that's always here
test -r /sw/bin/init.sh && . /sw/bin/init.sh
