#!/usr/bin/bash

PS1='\u@\h:\W$(__git_ps1 " (%s)")$ '
export HISTIGNORE="&:[bf]g:exit"
export HISTFILESIZE=10000
export EDITOR=vim
shopt -s histappend

# Environment #############################
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export GOBIN="~/Projects/golang/bin"
export PATH="~/bin:$PATH:$GOBIN"
export CLICOLOR=true
export LSCOLORS="exfxcxdxbxegedabagacad"
export PGDATA="/usr/local/pgsql/data"
export PAGER=less
export LESS="-RSX --tabs=4"

# Git Settings #############################
export GITHUB="git@github.com"

# Command Aliases ##########################
alias firefox=/Applications/Firefox.app/Contents/MacOS/firefox-bin
alias preview="open -a preview"
alias dotfiles="cd ~/.dotfiles"
alias gr=gitroot
alias g=git
alias r=rails
alias rails-src="cd ~/Projects/rails"
alias tmr="tmux attach-session"

# Weirdo Mac Aliases ##########################
alias md5sum=md5

# Include secured settings file
source ~/.dotfiles/secure/env.sh
source ~/.dotfiles/git/git-completion.bash
source ~/.dotfiles/git/helpers.sh
source ~/.dotfiles/bash.d/ssh.sh
check_ssh_agent

# RVM - Ruby Version Manager
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" && cd .

# End of file stuff that's always here
test -r /sw/bin/init.sh && . /sw/bin/init.sh
